### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by cobaltgit** [OldDigibox/sky-web-epg#11]
As evidenced below, when trying to load the favicon, Chrome presents a 404 error in the dev console, stating the favicon wasn't found, although you can find it in the source repository.
![image](https://user-images.githubusercontent.com/65132371/92779040-9dba4e80-f399-11ea-830a-72f339736faf.png)
![image](https://user-images.githubusercontent.com/65132371/92778588-38665d80-f399-11ea-986f-2f839f73cdf7.png)
As for Edge UWP, this is also the case except for the fact that the 404 error doesn't show up in their dev console. Screenshots can be found below.
![image](https://user-images.githubusercontent.com/65132371/92778861-75caeb00-f399-11ea-84eb-a88499678d77.png)
![image](https://user-images.githubusercontent.com/65132371/92778952-8a0ee800-f399-11ea-83f3-6b851e8eea56.png)

\

**Comment by sabianroberts** [comment]
You shouldn't really use Edge UWP anymore, as it's not recommended and there's a new Chromium version; but it's Chrome, and the same error will likely show up.

I recall removing the favicon and I may have told the HTML to try loading it anyway. However, the favicon is still there. It IS being tracked, the .gitignore file is not ignoring it. I'll look further into this, and I'll try to resolve it tonight.
