### ISSUE TITLE
Porting SWEPG to a component-based framework

### ISSUE THREAD

**Issue by cobaltgit** [OldDigibox/sky-web-epg#12]
This is in progress by the way, but we're gonna play around with eventually porting Sky Web EPG to a component-based framework, i.e React. Our newest member of the dev team, @JakeWorrell, has made a fork of the repository to use for the React port. Until requested, the fork of the React version won't be pushed onto the master repository

**Comment by sabianroberts** [comment]
Closing this issue. The React version of Sky Web EPG will never be on this repository. 5.10 is nearly finished, but I will think about it.
