### ISSUE TITLE
Add date to all subpages

### ISSUE THREAD

**Issue by cobaltgit** [OldDigibox/sky-web-epg#15]
3.8.8.ns (has a date)
![image](https://user-images.githubusercontent.com/65132371/94022838-6aba8680-fdad-11ea-8797-f29bbba779f8.png)
Sky Web EPG (no date)
![image](https://user-images.githubusercontent.com/65132371/94022948-8a51af00-fdad-11ea-95ec-0dfce81725db.png)
This also pretty much applies to almost every subpage on the EPG

**Comment by sabianroberts** [comment]
I'm going to start working on this now, I'll be using this for reference: https://www.arclab.com/en/kb/htmlcss/display-date-time-javascript-php-ssi.html

**Comment by sabianroberts** [comment]
https://stackoverflow.com/questions/64633412/how-do-i-display-the-current-date-and-time-in-a-specific-format

**Comment by sabianroberts** [comment]
This issue is now **FIXED** in commit 3cd2f101e501d5d5bc23b59bc35d0d19673d0c8e. Closing.
