### ISSUE TITLE
Figure out how Sky's online TV Guide works and implement it into the Sky Web EPG

### ISSUE THREAD

**Issue by sabianroberts** [OldDigibox/sky-web-epg#16]
Then we can really have it looking something like this..:
![image](https://user-images.githubusercontent.com/31491602/97593886-04530480-19fa-11eb-8153-96cb62c06ca2.png)

**Comment by 404invalid-user** [comment]
yes there probably is an api for it but it would require backend code which we cant do on github unless someone has a server that can run just backend for us
