### ISSUE TITLE
Background images load too slowly on slower connections

### ISSUE THREAD

**Issue by ghost** [OldDigibox/sky-web-epg#17]
I've noticed that the background images in Sky Web EPG are loading too slow even though they're only 800x600, to the point where I can see the data being loaded in. Not sure how this could happen.

**Comment by sabianroberts** [comment]
This also happens on my end, but I just ignored it because I thought it was just me. I'm not sure if there's anything I can do about this, unless there's a way to load all images at once whilst the page initialises.

**Comment by cobaltgit** [comment]
Have you tried using a CDN for the images?

**Comment by ghost** [comment]
I'll have a check to see the speed of access on other images, specifically FHD ones.

**Comment by cobaltgit** [comment]
Why not try using GitCDN.xyz for raw GitHub content

**Comment by sabianroberts** [comment]
> Have you tried using a CDN for the images?

@Crithub I'll look into it.

**Comment by sabianroberts** [comment]
Discord media URLs use CDN for their delivery. I'll try that.

**Comment by ghost** [comment]
Yeah I think this is a case of needing a CDN

**Comment by cobaltgit** [comment]
> Discord media URLs use CDN for their delivery. I'll try that.
Good thinking Batman

**Comment by ghost** [comment]
Didn't solve the issue.

**Comment by ghost** [comment]
Oh I've also noticed the last 2 backgrounds don't seem to be present at all.

**Comment by sabianroberts** [comment]
Just pushed c49abea07e4c5f157f65da812093582ebc3caaa8 in branch xmas (which is currently publishing for test purposes) and it seems to have solved it for me.

**Comment by sabianroberts** [comment]
> Didn't solve the issue.

Did you try Shift + F5?

**Comment by ghost** [comment]
That just clears the cache

**Comment by ghost** [comment]
Also, where do I access the site for the Xmas branch?

**Comment by sabianroberts** [comment]
The Xmas branch is currently published at https://olddigibox.github.io/sky-web-epg/ for test purposes

**Comment by sabianroberts** [comment]
Commit fa1198a124f96489947fda29309b6adde342141b now fixes the issue on master.

**Comment by sabianroberts** [comment]
@Crithub @brazier19971 Can you confirm that the issue is fixed on your end?

**Comment by cobaltgit** [comment]
> @Crithub @brazier19971 Can you confirm that the issue is fixed on your end?

[Here's a video clip](https://youtu.be/YM-sFek45l4) so you can see if it looks fast enough

**Comment by sabianroberts** [comment]
Looks fine. Closing now
