### ISSUE TITLE
Some colour buttons are misaligned

### ISSUE THREAD

**Issue by cobaltgit** [OldDigibox/sky-web-epg#18]
![image](https://user-images.githubusercontent.com/65132371/97790713-c48b4900-1bc2-11eb-837f-1bf3a86badff.png)
versus
![image](https://user-images.githubusercontent.com/65132371/97790725-ebe21600-1bc2-11eb-9263-505cd6bd0f07.png)

**Comment by sabianroberts** [comment]
Due to the CSS, this is unfixable.
