### ISSUE TITLE
Colours missing on phone numbers pages

### ISSUE THREAD

**Issue by cobaltgit** [OldDigibox/sky-web-epg#22]
![image](https://user-images.githubusercontent.com/65132371/97862585-80509380-1cfd-11eb-9993-adeffdca8339.png)
The only page that has colours is the 2nd page

**Comment by sabianroberts** [comment]
4aeb5d4c91786b27b39320c0d7d0050d95f3f911

**Comment by cobaltgit** [comment]
Done
