### ISSUE TITLE
Dates missing where FYI banners show

### ISSUE THREAD

**Issue by cobaltgit** [OldDigibox/sky-web-epg#23]
This issue resides particularly in the Box Office category and the FYI banner test in Interactive
![image](https://user-images.githubusercontent.com/65132371/97862685-ae35d800-1cfd-11eb-8120-c05c57326674.png)
![image](https://user-images.githubusercontent.com/65132371/97862706-b55ce600-1cfd-11eb-8161-d47eeeadebea.png)
Also add a BACK UP option for the FYI box test page

**Comment by sabianroberts** [comment]
0f1951fbb4d8bfc5f2ee93008b8c03154c2649ca
