### ISSUE TITLE
Add a theme switcher

### ISSUE THREAD

**Issue by sabianroberts** [OldDigibox/sky-web-epg#27]
This was done before but was removed.

**Comment by ry13y04** [comment]
I was thinking some sort of theme selector, where you can choose what background you want (_Launch EPG, Light Blue EPG, a Q like background, etc_) with one of them being a dark mode theme.

**Comment by sabianroberts** [comment]
I believe it was version 5.10-dv1 or 5.10-dv2 where @gaz-github implemented a dark theme so I could check that old version out and see how they did it

**Comment by sabianroberts** [comment]
Yep, it was 5.10-dv1. https://github.com/OldDigibox/sky-web-epg-ov/releases/tag/5.10-dv1

**Comment by ry13y04** [comment]
This was how it worked:
![image](https://user-images.githubusercontent.com/75205875/104124071-9060a100-5346-11eb-94f0-9449703afc0f.png)

**Comment by ry13y04** [comment]
If a theme selector is going to be included _(and if it is possible to do so)_ I have found a picture from June 2020.![image](https://user-images.githubusercontent.com/75205875/104449962-533f1d80-5597-11eb-981d-d6875629a78c.png)
Made by CHIT for his Q-Style 3.8.8 EPG, however it hasn't been completed.

**Comment by sabianroberts** [comment]
> If a theme selector is going to be included _(and if it is possible to do so)_ I have found a picture from June 2020.![image](https://user-images.githubusercontent.com/75205875/104449962-533f1d80-5597-11eb-981d-d6875629a78c.png)
> Made by CHIT for his Q-Style 3.8.8 EPG, however it hasn't been completed.

Thanks for this idea! There's only 4 themes in development at the moment - Default, Dark, 1998 and 2001 - but I will definitely approach Chelmsford IT about the Sky Q theme.

**Comment by sabianroberts** [comment]
I had attempted to do this with faccbb312ce3193e44056323e7ae94f337ff3f20, but failed. The code was not good.

I may need more help with this @OldDigibox/main-development
