### ISSUE TITLE
Manual Recording page has no Back Up option

### ISSUE THREAD

**Issue by ry13y04** [OldDigibox/sky-web-epg#28]
This is also the case on few other pages on the Web EPG when I was looking around.
![image](https://user-images.githubusercontent.com/75205875/104124048-6909d400-5346-11eb-954a-e122bd48a9f1.png)

**Comment by sabianroberts** [comment]
The "Add Manual Recording" button functions as the Back Up button.

**Comment by ry13y04** [comment]
Would it still be possible to add the corresponding text when you hover over the options, like the original EPG guide

**Comment by sabianroberts** [comment]
I'm afraid not. For the time being, I do not plan to add an unnecessary Back Up button. Thanks for suggesting the idea.
