### ISSUE TITLE
Primetime is the only HTTPS stream, all others are not secure

### ISSUE THREAD

**Issue by cobaltgit** [OldDigibox/sky-web-epg#3]
The Zeno M3U streams are hosted and linked over HTTP, which may cause browsers such as Chrome to bring up console warnings when attempting to play the streams sometimes.
![image](https://user-images.githubusercontent.com/65132371/85222624-a01d9580-b3b4-11ea-8672-cd9123e2097e.png)

**Comment by sabianroberts** [comment]
I might be able to resolve this, Zeno just contacted me asking what stations I wanted to host over HTTPS and I said "all of them." Now I'm just waiting for a reply.

**Comment by sabianroberts** [comment]
Zeno just contacted me and enabled HTTPS streaming on *all* Sky Web EPG stations!

**Comment by cobaltgit** [comment]
Note that the Primetime stream is the only true HTTPS stream

**Comment by sabianroberts** [comment]
I've contacted Zeno again, they haven't replied. I contacted them a week ago.

**Comment by sabianroberts** [comment]
Forgot to update this issue; Zeno contacted me and said that the HTTPS streams work. I will now see if that is the truth...

**Comment by sabianroberts** [comment]
Welp, lied to once again. Thanks Zeno. e4bc36b671ea66cb23bd4d89b4253baa266d0e21

**Comment by sabianroberts** [comment]
I don't know when this happened; but Zeno seems to have fixed the issue. I'll reopen this issue if the problem arises again, but for now... it's fixed. After nearly 3 months, it's finally been fixed.
