### ISSUE TITLE
Add video player with search and scan bar (see .sas in CSS) as player overlay

### ISSUE THREAD

**Issue by sabianroberts** [OldDigibox/sky-web-epg#4]

**Comment by cobaltgit** [comment]
How come this issue is still open anyway?

**Comment by sabianroberts** [comment]
> How come this issue is still open anyway?

@Crithub This issue is still open as it has not been completed yet.

**Comment by cobaltgit** [comment]
> > How come this issue is still open anyway?
> 
> @Crithub This issue is still open as it has not been completed yet.

How? I thought it was in the SAS test page

**Comment by sabianroberts** [comment]
> > > How come this issue is still open anyway?
> > 
> > 
> > @Crithub This issue is still open as it has not been completed yet.
> 
> How? I thought it was in the SAS test page

**It is not complete.** The current code is very buggy.
