### ISSUE TITLE
Implement feature to be able to navigate the menus with the number keys and arrow keys

### ISSUE THREAD

**Issue by ghost** [OldDigibox/sky-web-epg#7]

**Comment by sabianroberts** [comment]
What about up & down arrow keys?

**Comment by sabianroberts** [comment]
With the main element being `<li>`, I don't think this is possible without some advanced JS.

**Comment by cobaltgit** [comment]
> With the main element being `<li>`, I don't think this is possible without some advanced JS.

Why don't we map the Go Right/Left buttons to the left and right arrow keys for a start?

**Comment by sabianroberts** [comment]
That is actually possible, since their elements are `<a>`.

**Comment by cobaltgit** [comment]
> That is actually possible, since their elements are `<a>`.

Would we need some JS code for it or would it just be in the HTML
